services:
  # Tax API (External dependency)
  tax-api:
    image: ptsdocker16/interview-test-server
    ports:
      - "5001:5001"
    networks:
      - tax-network

  # Tax Calculator Backend
  tax-calculator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TAX_API_URL=http://tax-api:5001
    depends_on:
      - tax-api
    networks:
      - tax-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Unit Tests
  test-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    volumes:
      - coverage-data:/coverage
    networks:
      - tax-network
    profiles:
      - unit-test

  # Integration Tests via Newman
  newman:
    image: postman/newman:alpine
    volumes:
      - ./postman:/etc/newman
    command: run /etc/newman/tax-calculator.postman_collection.json --env-var "baseUrl=http://tax-calculator:8080"
    networks:
      - tax-network
    depends_on:
      - tax-calculator
    profiles:
      - integration-test

networks:
  tax-network:
    driver: bridge

volumes:
  coverage-data: